### PR TITLE
Added file upload.

### PR DESCRIPTION
**Pull request by bennetgallein**
It needs some improvement, but it's tested and works..

Proof

### CODE REVIEW

**Comment by bennetgallein** [comment]
Also don't forget to update packagist! 👍

**Comment by bennetgallein** [comment]
push

**Comment by nopjmp** [comment]
This stops other fields from being used if there is a file. You can upload a file and still have text (just not embeds). #9 included your changes without attribution and modified them slightly also. If you want to fix that problem, I'll pull your code in. (You did include tts support in this, but I'll allow it since it's such a tiny addition)

Hint: I put some details in #9 in regards to what is probably the best approach which is always sending form fields / post fields and throwing an exception if embeds and file are both used (Discord states this is not possible on their API docs)

**Comment by bennetgallein** [comment]
I'm gonna have a look at that..

**Comment by nopjmp** [comment]
closing due to age, resubmit with the requested changes and I'll pull in the changes

**Pull request closed without merging**
