### PR TITLE
Add support for uploading files

### PR DESCRIPTION
**Pull request by JiFish**
Is this project still active? I hope so, other alternatives are way too over-engineered.

Adds support for attaching files. Use `addFile` to add a file on disc, or `addStringFile` to create the file programmatically. Also added `clearFiles` to clear the list. Added support to specify mime type, although discord seems to mostly ignore this value.

Added 200 as a valid return code as this is what discord returns when using Content-Type: multipart/form-data.

Finally removed unused variable `$json_result`

Does no file-size checking, as the maximum depends on how boosted the server is.

#1

### CODE REVIEW

**Comment by nopjmp** [comment]
I'm not currently using it. But I'm more than happy to maintain it as it's a very small and simple project! Thanks for the contribution.

**Comment by JiFish** [comment]
Thank you.

Could I trouble you to push an update to packagist?

**Comment by nopjmp** [comment]
I'll have it out in a bit. I reviewed and merged it on my phone while I was shopping :)

**Comment by nopjmp** [comment]
@JiFish pushed as 0.4.0 since it's a new feature and I'm not sure if this will break anything yet as I've not tested it.

**Comment by JiFish** [comment]
Apologies, I didn't mean to rush you. Thanks. 👍

**Pull request merged**
